config/routes.rb
Rails.application.routes.draw do
  resources :payment_frequencies
  resources :credit_types
  resources :credit_applications
  devise_for :users
  resources :bills
  root 'homes#index'
  resources :business_partners
  resources :business_partner_types
  resources :coins
  resources :products
  resources :storehouses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :business_partner
  belongs_to :coin
  belongs_to :bill_type
  belongs_to :payment_type
end

app/models/bill_type.rb
class BillType < ApplicationRecord
end

app/models/business_partner.rb
class BusinessPartner < ApplicationRecord
  validates :name, presence: true
  validates :id_number, presence: true

  belongs_to :business_partner_type
  belongs_to :coin

  def display_name
    self.name
  end
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/coin.rb
class Coin < ApplicationRecord
  CORDOBA = 1
  DOLAR = 2

  def display_name
    self.symbol
  end
end

app/models/credit_application.rb
class CreditApplication < ApplicationRecord
  belongs_to :business_partner
  belongs_to :credit_type
  belongs_to :payment_frequency
  belongs_to :coin
  belongs_to :statu
end

app/models/credit_type.rb
class CreditType < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/payment_frequency.rb
class PaymentFrequency < ApplicationRecord
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord

  def display_name
    self.nombre
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/statu.rb
class Statu < ApplicationRecord
end

app/models/storehouse.rb
class Storehouse < ApplicationRecord
  validates :name, presence: true

  belongs_to :storehouses_type


  def display_name
    self.name
  end
end

app/models/storehouses_type.rb
class StorehousesType < ApplicationRecord
  NINGUNO = 1
  VENTA = 2
  COMPRA = 3
  COMPRA_Y_VENTA = 4

  def display_name
    self.name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:business_partner_id, :coin_id, :bill_type_id, :nota, :numero, :fecha, :fecha_de_vencimiento, :anulada, :payment_type_id)
    end
end

app/controllers/coins_controller.rb
##
# Manejador de peticiones dirigidas a pacientes.
class CoinsController < ApplicationController
  include FormConcern

  private

  ##
  # Método de encapsulacion de los parametros permitodos en este controller.
    def coin_params
      params.require(:coin).permit(:id, :description, :symbol)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/credit_types_helper.rb
module CreditTypesHelper
end

app/helpers/form_helper.rb
module FormHelper

  def select_input(form, record, field, collection, options = {})
    _, grid_size, field_message, html_options , options = options_input(field, options, record)

    render(partial: 'inputs/select', layout: 'layouts/form',
           locals: {
             f: form, field: field, record: record, field_message: field_message,
             grid_size: grid_size, collection: collection, options: options,
             html_options: html_options
            })
  end

  def check_box_input(form, record, field, options = {})
    label, grid_size, field_message, html_options , options = options_input(field, options, record)

    render(partial: 'inputs/check_box', layout: 'layouts/form',
           locals: {
             f: form, field: field, record: record, field_message: field_message,
             grid_size: grid_size, label: label, options: options.merge(html_options)
           })
  end

  def text_input(form, record, field, options = {})
    _, grid_size, field_message, html_options , options = options_input(field, options, record)

    render(partial: 'inputs/text', layout: 'layouts/form',
           locals: {
             f: form, field: field, record: record, field_message: field_message,
             grid_size: grid_size, options: options.merge(html_options)
           })
  end

  def text_area_input(form, record, field, options = {})
    _, grid_size, field_message, html_options , options = options_input(field, options, record)

    render(partial: 'inputs/text_area', layout: 'layouts/form',
           locals: {
             f: form, field: field, record: record, field_message: field_message,
             grid_size: grid_size, options: options.merge(html_options)
           })
  end

  private

  def options_input(field, options, record)
    field_message = options[:field_message] || field
    error_messages = error_message(record, field_message)
    [
      options[:label],
      options[:grid_size] || 12,
      field_message,
      error_messages.merge(options[:html_options] || {}) || {},
      options[:options] || {}
    ]
  end

  def error_message(record, field_message)
    return {} if record.errors.messages[field_message].blank?

    {
      data: {
        toggle: 'tooltip',
        placement: 'top',
      },
      title: record.errors.messages[field_message].first.titlecase
    }
  end
end

app/helpers/menu_helper.rb
module MenuHelper
  def main_menu_items
    menu_root = [Rails.root, 'config', 'menu', 'default'].join('/')

    File.open([menu_root, 'menu.yml'].join('/')) { |file| YAML.load(file) }.map do |i|
      file_name = [menu_root, "#{i[:name]}.yml"].join('/')
      File.open([menu_root, "#{i[:name]}.yml"].join('/')) { |file| YAML.load(file) } if File.exists?(file_name)
    end.flatten.compact
  end

  def menu_items
    menu_items = []
    main_menu_items.each do |menu_item|
      menu_items << item(menu_item)
    end
    menu_items.compact
  end

  def item(menu_item)
    items = menu_item[:items]
    if items.present?
      sub_menu_items = []
      items.each do |item|
        sub_menu_items << item(item)
      end
      sub_menu_items = sub_menu_items.compact
      if sub_menu_items.present?
        menu_item[:items] = sub_menu_items
      end
    end

    menu_item
  end
end

app/views/bills/_form.html.erb
<div class='row'>
  <%= form_for(bill) do |f| %>
    <div class="row">
      <% if bill.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

          <ul>
            <% bill.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    <div class="row">
      <%= f.hidden_field :bill_type_id %>
      <div class="row">
        <div class="input-field col s5">
          <%= f.select :business_partner_id,
            BusinessPartner.all.collect {|p| [ p.descripcion, p.id ] },
            { include_blank: 'Cliente' }
           %>
        </div>
        <div class="input-field col s3">
          <%= f.label :numero %>
          <%= f.text_field :numero %>
        </div>
        <div class="input-field col s2">
          <%= f.check_box :anulada %>
          <%= f.label :anulada, 'Anulada?' %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s5">
          <%= f.select :coin_id,
            Coin.all.collect {|c| [c.simbolo, c.id]},
            { include_blank: 'Moneda'}%>
        </div>
        <div class="input-field col s5">
            <%= f.label :fecha %>
            <%= f.text_field :fecha, class: 'datepicker' %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s5">
          <%= f.select :payment_type_id,
            PaymentType.all.collect {|c| [c.display_name, c.id]},
            { include_blank: 'Moneda'}%>
        </div>
        <div class="input-field col s5">
            <%= f.label :fecha_de_vencimiento %>
            <%= f.text_field :fecha_de_vencimiento, class: 'datepicker' %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <%= f.label :nota %>
          <%= f.text_area :nota, class: 'materialize-textarea' %>
        </div>
      </div>
      <div class="row">
        <button type="submit" name="commit" class="btn waves-effect waves-light">
          Guardar
          <i class="material-icons right">send</i>
        </button>
      </div>
    </div>
  <% end %>
</div>

app/views/bills/edit.html.erb
<h1>Factura</h1>

<%= render 'form', bill: @bill %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bills</h1>

<table>
  <thead>
    <tr>
      <th>Business partner</th>
      <th>Coin</th>
      <th>Bill type</th>
      <th>Nota</th>
      <th>Numero</th>
      <th>Fecha</th>
      <th>Fecha de vencimiento</th>
      <th>Anulada</th>
      <th>Payment type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.business_partner %></td>
        <td><%= bill.coin %></td>
        <td><%= bill.bill_type %></td>
        <td><%= bill.nota %></td>
        <td><%= bill.numero %></td>
        <td><%= bill.fecha %></td>
        <td><%= bill.fecha_de_vencimiento %></td>
        <td><%= bill.anulada %></td>
        <td><%= bill.payment_type %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>Nueva Factura</h1>

<%= render 'form', bill: @bill %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Business partner:</strong>
  <%= @bill.business_partner %>
</p>

<p>
  <strong>Coin:</strong>
  <%= @bill.coin %>
</p>

<p>
  <strong>Bill type:</strong>
  <%= @bill.bill_type %>
</p>

<p>
  <strong>Nota:</strong>
  <%= @bill.nota %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @bill.numero %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @bill.fecha %>
</p>

<p>
  <strong>Fecha de vencimiento:</strong>
  <%= @bill.fecha_de_vencimiento %>
</p>

<p>
  <strong>Anulada:</strong>
  <%= @bill.anulada %>
</p>

<p>
  <strong>Payment type:</strong>
  <%= @bill.payment_type %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>