config/routes.rb
Rails.application.routes.draw do
  resources :payment_frequencies
  resources :credit_types
  resources :credit_applications
  devise_for :users
  resources :bills
  root 'homes#index'
  resources :business_partners
  resources :business_partner_types
  resources :coins
  resources :products
  resources :storehouses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :business_partner
  belongs_to :coin
  belongs_to :bill_type
  belongs_to :payment_type
end

app/models/bill_type.rb
class BillType < ApplicationRecord
end

app/models/business_partner.rb
class BusinessPartner < ApplicationRecord
  validates :name, presence: true
  validates :id_number, presence: true

  belongs_to :business_partner_type
  belongs_to :coin

  def display_name
    self.name
  end
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/coin.rb
class Coin < ApplicationRecord
  CORDOBA = 1
  DOLAR = 2

  def display_name
    self.symbol
  end
end

app/models/credit_application.rb
class CreditApplication < ApplicationRecord
  belongs_to :business_partner
  belongs_to :credit_type
  belongs_to :payment_frequency
  belongs_to :coin
  belongs_to :statu
end

app/models/credit_type.rb
class CreditType < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/payment_frequency.rb
class PaymentFrequency < ApplicationRecord
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord

  def display_name
    self.nombre
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/statu.rb
class Statu < ApplicationRecord
end

app/models/storehouse.rb
class Storehouse < ApplicationRecord
  validates :name, presence: true

  belongs_to :storehouses_type


  def display_name
    self.name
  end
end

app/models/storehouses_type.rb
class StorehousesType < ApplicationRecord
  NINGUNO = 1
  VENTA = 2
  COMPRA = 3
  COMPRA_Y_VENTA = 4

  def display_name
    self.name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/payment_frequencies_controller.rb
class PaymentFrequenciesController < ApplicationController
  before_action :set_payment_frequency, only: [:show, :edit, :update, :destroy]

  # GET /payment_frequencies
  # GET /payment_frequencies.json
  def index
    @payment_frequencies = PaymentFrequency.all
  end

  # GET /payment_frequencies/1
  # GET /payment_frequencies/1.json
  def show
  end

  # GET /payment_frequencies/new
  def new
    @payment_frequency = PaymentFrequency.new
  end

  # GET /payment_frequencies/1/edit
  def edit
  end

  # POST /payment_frequencies
  # POST /payment_frequencies.json
  def create
    @payment_frequency = PaymentFrequency.new(payment_frequency_params)

    respond_to do |format|
      if @payment_frequency.save
        format.html { redirect_to @payment_frequency, notice: 'Payment frequency was successfully created.' }
        format.json { render :show, status: :created, location: @payment_frequency }
      else
        format.html { render :new }
        format.json { render json: @payment_frequency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_frequencies/1
  # PATCH/PUT /payment_frequencies/1.json
  def update
    respond_to do |format|
      if @payment_frequency.update(payment_frequency_params)
        format.html { redirect_to @payment_frequency, notice: 'Payment frequency was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_frequency }
      else
        format.html { render :edit }
        format.json { render json: @payment_frequency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_frequencies/1
  # DELETE /payment_frequencies/1.json
  def destroy
    @payment_frequency.destroy
    respond_to do |format|
      format.html { redirect_to payment_frequencies_url, notice: 'Payment frequency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_frequency
      @payment_frequency = PaymentFrequency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_frequency_params
      params.require(:payment_frequency).permit(:descripcion, :activo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/credit_types_helper.rb
module CreditTypesHelper
end

app/helpers/form_helper.rb
module FormHelper

  def select_input(form, record, field, collection, options = {})
    _, grid_size, field_message, html_options , options = options_input(field, options, record)

    render(partial: 'inputs/select', layout: 'layouts/form',
           locals: {
             f: form, field: field, record: record, field_message: field_message,
             grid_size: grid_size, collection: collection, options: options,
             html_options: html_options
            })
  end

  def check_box_input(form, record, field, options = {})
    label, grid_size, field_message, html_options , options = options_input(field, options, record)

    render(partial: 'inputs/check_box', layout: 'layouts/form',
           locals: {
             f: form, field: field, record: record, field_message: field_message,
             grid_size: grid_size, label: label, options: options.merge(html_options)
           })
  end

  def text_input(form, record, field, options = {})
    _, grid_size, field_message, html_options , options = options_input(field, options, record)

    render(partial: 'inputs/text', layout: 'layouts/form',
           locals: {
             f: form, field: field, record: record, field_message: field_message,
             grid_size: grid_size, options: options.merge(html_options)
           })
  end

  def text_area_input(form, record, field, options = {})
    _, grid_size, field_message, html_options , options = options_input(field, options, record)

    render(partial: 'inputs/text_area', layout: 'layouts/form',
           locals: {
             f: form, field: field, record: record, field_message: field_message,
             grid_size: grid_size, options: options.merge(html_options)
           })
  end

  private

  def options_input(field, options, record)
    field_message = options[:field_message] || field
    error_messages = error_message(record, field_message)
    [
      options[:label],
      options[:grid_size] || 12,
      field_message,
      error_messages.merge(options[:html_options] || {}) || {},
      options[:options] || {}
    ]
  end

  def error_message(record, field_message)
    return {} if record.errors.messages[field_message].blank?

    {
      data: {
        toggle: 'tooltip',
        placement: 'top',
      },
      title: record.errors.messages[field_message].first.titlecase
    }
  end
end

app/helpers/menu_helper.rb
module MenuHelper
  def main_menu_items
    menu_root = [Rails.root, 'config', 'menu', 'default'].join('/')

    File.open([menu_root, 'menu.yml'].join('/')) { |file| YAML.load(file) }.map do |i|
      file_name = [menu_root, "#{i[:name]}.yml"].join('/')
      File.open([menu_root, "#{i[:name]}.yml"].join('/')) { |file| YAML.load(file) } if File.exists?(file_name)
    end.flatten.compact
  end

  def menu_items
    menu_items = []
    main_menu_items.each do |menu_item|
      menu_items << item(menu_item)
    end
    menu_items.compact
  end

  def item(menu_item)
    items = menu_item[:items]
    if items.present?
      sub_menu_items = []
      items.each do |item|
        sub_menu_items << item(item)
      end
      sub_menu_items = sub_menu_items.compact
      if sub_menu_items.present?
        menu_item[:items] = sub_menu_items
      end
    end

    menu_item
  end
end

app/helpers/payment_frequencies_helper.rb
module PaymentFrequenciesHelper
end

app/views/payment_frequencies/_form.html.erb
<%= form_for(payment_frequency) do |f| %>
  <% if payment_frequency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment_frequency.errors.count, "error") %> prohibited this payment_frequency from being saved:</h2>

      <ul>
      <% payment_frequency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>

  <div class="field">
    <%= f.label :activo %>
    <%= f.check_box :activo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_frequencies/edit.html.erb
<h1>Editing Payment Frequency</h1>

<%= render 'form', payment_frequency: @payment_frequency %>

<%= link_to 'Show', @payment_frequency %> |
<%= link_to 'Back', payment_frequencies_path %>

app/views/payment_frequencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payment Frequencies</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Activo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_frequencies.each do |payment_frequency| %>
      <tr>
        <td><%= payment_frequency.descripcion %></td>
        <td><%= payment_frequency.activo %></td>
        <td><%= link_to 'Show', payment_frequency %></td>
        <td><%= link_to 'Edit', edit_payment_frequency_path(payment_frequency) %></td>
        <td><%= link_to 'Destroy', payment_frequency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment Frequency', new_payment_frequency_path %>

app/views/payment_frequencies/new.html.erb
<h1>New Payment Frequency</h1>

<%= render 'form', payment_frequency: @payment_frequency %>

<%= link_to 'Back', payment_frequencies_path %>

app/views/payment_frequencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @payment_frequency.descripcion %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @payment_frequency.activo %>
</p>

<%= link_to 'Edit', edit_payment_frequency_path(@payment_frequency) %> |
<%= link_to 'Back', payment_frequencies_path %>