config/routes.rb
Rails.application.routes.draw do
  resources :payment_frequencies
  resources :credit_types
  resources :credit_applications
  devise_for :users
  resources :bills
  root 'homes#index'
  resources :business_partners
  resources :business_partner_types
  resources :coins
  resources :products
  resources :storehouses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :business_partner
  belongs_to :coin
  belongs_to :bill_type
  belongs_to :payment_type
end

app/models/bill_type.rb
class BillType < ApplicationRecord
end

app/models/business_partner.rb
class BusinessPartner < ApplicationRecord
  validates :name, presence: true
  validates :id_number, presence: true

  belongs_to :business_partner_type
  belongs_to :coin

  def display_name
    self.name
  end
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/coin.rb
class Coin < ApplicationRecord
  CORDOBA = 1
  DOLAR = 2

  def display_name
    self.symbol
  end
end

app/models/credit_application.rb
class CreditApplication < ApplicationRecord
  belongs_to :business_partner
  belongs_to :credit_type
  belongs_to :payment_frequency
  belongs_to :coin
  belongs_to :statu
end

app/models/credit_type.rb
class CreditType < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/payment_frequency.rb
class PaymentFrequency < ApplicationRecord
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord

  def display_name
    self.nombre
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/statu.rb
class Statu < ApplicationRecord
end

app/models/storehouse.rb
class Storehouse < ApplicationRecord
  validates :name, presence: true

  belongs_to :storehouses_type


  def display_name
    self.name
  end
end

app/models/storehouses_type.rb
class StorehousesType < ApplicationRecord
  NINGUNO = 1
  VENTA = 2
  COMPRA = 3
  COMPRA_Y_VENTA = 4

  def display_name
    self.name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/credit_applications_controller.rb
class CreditApplicationsController < ApplicationController
  before_action :set_credit_application, only: [:show, :edit, :update, :destroy]

  # GET /credit_applications
  # GET /credit_applications.json
  def index
    @credit_applications = CreditApplication.all
  end

  # GET /credit_applications/1
  # GET /credit_applications/1.json
  def show
  end

  # GET /credit_applications/new
  def new
    @credit_application = CreditApplication.new
  end

  # GET /credit_applications/1/edit
  def edit
  end

  # POST /credit_applications
  # POST /credit_applications.json
  def create
    @credit_application = CreditApplication.new(credit_application_params)

    respond_to do |format|
      if @credit_application.save
        format.html { redirect_to @credit_application, notice: 'Credit application was successfully created.' }
        format.json { render :show, status: :created, location: @credit_application }
      else
        format.html { render :new }
        format.json { render json: @credit_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_applications/1
  # PATCH/PUT /credit_applications/1.json
  def update
    respond_to do |format|
      if @credit_application.update(credit_application_params)
        format.html { redirect_to @credit_application, notice: 'Credit application was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_application }
      else
        format.html { render :edit }
        format.json { render json: @credit_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_applications/1
  # DELETE /credit_applications/1.json
  def destroy
    @credit_application.destroy
    respond_to do |format|
      format.html { redirect_to credit_applications_url, notice: 'Credit application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_application
      @credit_application = CreditApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_application_params
      params.require(:credit_application).permit(:business_partner_id, :fecha, :fecha_de_vencimiento, :credit_type_id, :payment_frequency_id, :payment_number, :monto, :coin_id, :nota, :status_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/credit_applications_helper.rb
module CreditApplicationsHelper
end

app/helpers/credit_types_helper.rb
module CreditTypesHelper
end

app/helpers/form_helper.rb
module FormHelper

  def select_input(form, record, field, collection, options = {})
    _, grid_size, field_message, html_options , options = options_input(field, options, record)

    render(partial: 'inputs/select', layout: 'layouts/form',
           locals: {
             f: form, field: field, record: record, field_message: field_message,
             grid_size: grid_size, collection: collection, options: options,
             html_options: html_options
            })
  end

  def check_box_input(form, record, field, options = {})
    label, grid_size, field_message, html_options , options = options_input(field, options, record)

    render(partial: 'inputs/check_box', layout: 'layouts/form',
           locals: {
             f: form, field: field, record: record, field_message: field_message,
             grid_size: grid_size, label: label, options: options.merge(html_options)
           })
  end

  def text_input(form, record, field, options = {})
    _, grid_size, field_message, html_options , options = options_input(field, options, record)

    render(partial: 'inputs/text', layout: 'layouts/form',
           locals: {
             f: form, field: field, record: record, field_message: field_message,
             grid_size: grid_size, options: options.merge(html_options)
           })
  end

  def text_area_input(form, record, field, options = {})
    _, grid_size, field_message, html_options , options = options_input(field, options, record)

    render(partial: 'inputs/text_area', layout: 'layouts/form',
           locals: {
             f: form, field: field, record: record, field_message: field_message,
             grid_size: grid_size, options: options.merge(html_options)
           })
  end

  private

  def options_input(field, options, record)
    field_message = options[:field_message] || field
    error_messages = error_message(record, field_message)
    [
      options[:label],
      options[:grid_size] || 12,
      field_message,
      error_messages.merge(options[:html_options] || {}) || {},
      options[:options] || {}
    ]
  end

  def error_message(record, field_message)
    return {} if record.errors.messages[field_message].blank?

    {
      data: {
        toggle: 'tooltip',
        placement: 'top',
      },
      title: record.errors.messages[field_message].first.titlecase
    }
  end
end

app/helpers/menu_helper.rb
module MenuHelper
  def main_menu_items
    menu_root = [Rails.root, 'config', 'menu', 'default'].join('/')

    File.open([menu_root, 'menu.yml'].join('/')) { |file| YAML.load(file) }.map do |i|
      file_name = [menu_root, "#{i[:name]}.yml"].join('/')
      File.open([menu_root, "#{i[:name]}.yml"].join('/')) { |file| YAML.load(file) } if File.exists?(file_name)
    end.flatten.compact
  end

  def menu_items
    menu_items = []
    main_menu_items.each do |menu_item|
      menu_items << item(menu_item)
    end
    menu_items.compact
  end

  def item(menu_item)
    items = menu_item[:items]
    if items.present?
      sub_menu_items = []
      items.each do |item|
        sub_menu_items << item(item)
      end
      sub_menu_items = sub_menu_items.compact
      if sub_menu_items.present?
        menu_item[:items] = sub_menu_items
      end
    end

    menu_item
  end
end

app/views/credit_applications/_form.html.erb
<div class='row'>
  <%= form_for(credit_application) do |f| %>
    <div class='row'>
      <% if credit_application.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(credit_application.errors.count, "error") %> prohibited this credit_application from being saved:</h2>

          <ul>
          <% credit_application.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    <div class='row'>
      <div class='col s6'>
        <div class='field'>
          <%= f.select :business_partner_id,
            BusinessPartner.all.collect {|b| [ b.display_name, b.id ]},
            { include_blank: '--- Socio de Negocios ---'}
          %>
        </div>
        <div class="field">
          <%= f.select :credit_type_id,
            CreditType.all.collect {|c| [c.display_name, c.id ]},
            { include_blank: '--- Tipo de Crédito ---'}
          %>
        </div>
        <div class="field">
          <%= f.select :coin_id,
            Coin.all.collect {|c| [ c.display_name, c.id]},
            { include_blank: '--- Tipo de Moneda ---'}
          %>
        </div>
        <div class="field">
          <%= f.label :monto %>
          <%= f.number_field :monto %>
        </div>
      </div>

      <div class='col s6'>
        <div class="field">
          <%= f.label :fecha %>
          <%= f.text_field :fecha, class: 'datepicker' %>
        </div>

        <div class="field">
          <%= f.label :fecha_de_vencimiento %>
          <%= f.text_field :fecha_de_vencimiento, class: 'datepicker' %>
        </div>
        <div class="field">
          <%= f.label :nota %>
          <%= f.text_area :nota %>
        </div>
      </div>
    </div>
  <div class="field">
    <%= f.label :payment_frequency_id %>
    <%= f.text_field :payment_frequency_id %>
  </div>

  <div class="field">
    <%= f.label :payment_number %>
    <%= f.number_field :payment_number %>
  </div>

  <div class="field">
    <%= f.label :statu_id %>
    <%= f.text_field :statu_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_applications/edit.html.erb
<h1>Editing Credit Application</h1>

<%= render 'form', credit_application: @credit_application %>

<%= link_to 'Show', @credit_application %> |
<%= link_to 'Back', credit_applications_path %>

app/views/credit_applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Credit Applications</h1>

<table>
  <thead>
    <tr>
      <th>Business partner</th>
      <th>Fecha</th>
      <th>Fecha de vencimiento</th>
      <th>Credit type</th>
      <th>Payment frequency</th>
      <th>Payment number</th>
      <th>Monto</th>
      <th>Coin</th>
      <th>Nota</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_applications.each do |credit_application| %>
      <tr>
        <td><%= credit_application.business_partner %></td>
        <td><%= credit_application.fecha %></td>
        <td><%= credit_application.fecha_de_vencimiento %></td>
        <td><%= credit_application.credit_type %></td>
        <td><%= credit_application.payment_frequency %></td>
        <td><%= credit_application.payment_number %></td>
        <td><%= credit_application.monto %></td>
        <td><%= credit_application.coin %></td>
        <td><%= credit_application.nota %></td>
        <td><%= credit_application.status %></td>
        <td><%= link_to 'Show', credit_application %></td>
        <td><%= link_to 'Edit', edit_credit_application_path(credit_application) %></td>
        <td><%= link_to 'Destroy', credit_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit Application', new_credit_application_path %>

app/views/credit_applications/new.html.erb
<h1>New Credit Application</h1>

<%= render 'form', credit_application: @credit_application %>

<%= link_to 'Back', credit_applications_path %>

app/views/credit_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Business partner:</strong>
  <%= @credit_application.business_partner %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @credit_application.fecha %>
</p>

<p>
  <strong>Fecha de vencimiento:</strong>
  <%= @credit_application.fecha_de_vencimiento %>
</p>

<p>
  <strong>Credit type:</strong>
  <%= @credit_application.credit_type %>
</p>

<p>
  <strong>Payment frequency:</strong>
  <%= @credit_application.payment_frequency %>
</p>

<p>
  <strong>Payment number:</strong>
  <%= @credit_application.payment_number %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @credit_application.monto %>
</p>

<p>
  <strong>Coin:</strong>
  <%= @credit_application.coin %>
</p>

<p>
  <strong>Nota:</strong>
  <%= @credit_application.nota %>
</p>

<p>
  <strong>Status:</strong>
  <%= @credit_application.status %>
</p>

<%= link_to 'Edit', edit_credit_application_path(@credit_application) %> |
<%= link_to 'Back', credit_applications_path %>